### ISSUE TITLE
[Home page] Add Sponsors section

### ISSUE THREAD

**Issue by taesungh** [HackAtUCI/HackUCI-Site#20]
All of our hackathon sponsors should be displayed on our Home page
- Include logos and links in sponsors section
- Provide sponsor information through reusable format (e.g. `src/assets/data/sponsors.json`)
- Include effect to slightly enlarge logo on hover

**Comment by taesungh** [comment]
Due to a sponsorship agreement, corporate is requesting to have at least the Sticker Mule logo with an affiliate link to https://mule.to/p3gu on the site soon so they can proceed with ordering stickers with sponsorship credit.

**Comment by samderanova** [comment]
Got it, I'll work on this when I can.

**Comment by Pegysus** [comment]
Yeah, I can work on it.

**Comment by Pegysus** [comment]
@samderanova @taesungh should I use the sponsors provided in the google drive or the figma?

**Comment by samderanova** [comment]
You should use the ones in Google Drive, since those are our sponsors for this year. We prefer vectorized images so only use those for now.

For some companies, there are multiple vectorized logos available. Pretty sure it doesn't matter which one you use.

**Comment by taesungh** [comment]
Current priority is just the Sticker Mule logo and affiliate link, we can add the others later.

**Comment by samderanova** [comment]
We need to add the rest of the sponsor logos.
