### ISSUE TITLE
Design participant Portal page

### ISSUE THREAD

**Issue by taesungh** [HackAtUCI/HackUCI-Site#31]
Participants with an account should be able to log in to view their Portal which displays status information. Different views and messages could include
- Application Submission
  - Before applying: show link for user to apply (could alternatively omit this status and just redirect to application)
  - After applying: show submitted message with submission time
    - Next steps: wait for decisions
- Application Decision
  - Rejected: show rejection message
  - Accepted: show acceptance message
    - Next steps: complete RSVP and waiver
- Attendance Confirmation: show completion of waiver and RSVP
  - Next steps: show up to the event

The vision is to implement these statuses as a growing vertical timeline (perhaps in reverse chronological order?) where previous statuses are always shown (unlike previous years). For all statuses besides Rejected, there will be a temporary "Next Steps" status describing what's next. Each status can be associated with a status icon (e.g. not started, pending, completed).

For the initial launch, have at least the "After applying" view ready.

**Comment by taesungh** [comment]
@njhuey, could we also add an item to the Vertical Timeline for RSVP status:
- pending icon with "Confirm Attendance" message if not confirmed
- check icon with "Attendance Confirmed" message if confirmed

**Comment by njhuey** [comment]
![Screen Shot 2023-01-30 at 9 49 31 PM](https://user-images.githubusercontent.com/81263982/215676760-f4469823-0d8e-4008-9b7d-648863753e03.png)
